replicaCount: 2

image:
  repository: 234164312932.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DEBUG: "False"
  DATABASE_URL: "postgres://user:password@db-host:5432/dbname"
  SECRET_KEY: "your-super-secret-key"