apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  DEBUG: {{ .Values.env.DEBUG | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}